# Generated by Django 3.2.10 on 2023-07-31 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Knagu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sub',
            new_name='Student',
        ),
    ]
